Refactor bipart codes
KatanaGraph/katana pull request #512
Opened 2020-09-27 10:11 UTC by nicelhc13

This commit removes inefficient stealing, renames classes and variables, and encapsulates fields.
Since the modifications are big enough, I stopped further refactoring and requested this PR first.
Remaining tasks are 1) need to think about vector types among PODResizableArray, std::vector and galois::gstl::Vector and 2) replacing reference parameter to be modified with pointers to follow the katana code conventions.

I will proceed this work through the next PR.

2020-09-28 15:47 UTC, roshandathathri requested changes
Object parameters should be `const Type&` if it is passed by value and `Type *` if it is passed by reference.

If a class is mostly just getters and setters, then it is better as a struct.

2020-09-28 15:47 UTC, roshandathathri commented on libgalois/include/galois/graphs/HyperGraph.h
> +    matched_ = false;
Drop. Already set in InitCoarsen().

2020-09-28 15:47 UTC, roshandathathri commented on libgalois/include/galois/graphs/HyperGraph.h
> +    partition_ = 0;
Move these two assignments to InitCoarsen() and rename that function to Init().

2020-09-28 15:47 UTC, roshandathathri commented on libgalois/include/galois/graphs/HyperGraph.h
> +  galois::CopyableAtomic<NetnumTy> netnum_;
This is another case where "struct" is more appropriate than "class". The class is filled with getters and setters and other than the constructor, there is only one public non-getter/setter function, which is InitRefine(). 

If you're going to keep it as a "class", make sure all the getters are const functions.

2020-09-28 15:47 UTC, roshandathathri commented on libgalois/include/galois/graphs/HyperGraph.h
> +class MetisGraph {
Same comment as above.

2020-09-28 15:47 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Helper.h
> +ParallelPrefixSum(galois::LargeArray<T>& prefix_sum) {
This should be in libgalois as this is not specific to bipart.

Moreover, there is an existing parallel prefix sum in libpangolin/include/pangolin/scan.h. Move that to libgalois and merge this function with that.

You can do this in a subsequent PR if you want.

2020-09-28 15:47 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Helper.h
> +void InitGain(HyperGraph& g);
`const HyperGraph&` (assuming you're not modifying the reference).

2020-09-28 15:47 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Bipart.cpp
> +ComputingCut(HyperGraph& g) {
`const HyperGraph&`

2020-09-28 15:47 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Bipart.cpp
> +    std::vector<galois::InsertBag<GNode>>& mem_hedges_of_parts,
`const Type&` for all 3 references.

2020-09-28 15:47 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Bipart.cpp
> +    std::vector<uint32_t>& num_hedges_per_partition, const uint32_t num_hedges,
Ditto

2020-09-28 15:47 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Bipart.cpp
> +          return;
Return as in break from the loop or return from the function?

2020-09-28 15:47 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Bipart.cpp
> +    std::vector<uint32_t>& pgraph_index, HyperGraph* graph,
Ditto

2020-09-28 15:47 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Helper.cpp
> +InitNodes(HyperGraph& graph, uint32_t num_hedges) {
`const HyperGraph&`

2020-09-28 15:47 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Helper.cpp
> +    HyperGraph& graph, std::vector<GNode>& nodes, uint32_t end_offset = 0) {
`const Type&`

2020-09-28 15:47 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Helper.cpp
> -InitGain(GGraph& g) {
Ditto

2020-09-28 15:47 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Helper.cpp
> +    std::vector<HyperGraph*>& g) {
Ditto

2020-09-28 15:47 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Metric.cpp
> +GraphStat(HyperGraph& graph) {
Ditto

2020-09-28 15:47 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Partitioning.cpp
>      std::vector<std::pair<uint32_t, uint32_t>>& combined_node_list) {
Ditto

2020-09-28 15:47 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Refine.cpp
> +ResetCounter(HyperGraph& g) {
Ditto

2020-09-28 15:47 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Refine.cpp
> +ParallelMakingbalance(HyperGraph& g, float tol) {
Ditto

2020-09-28 19:18 UTC, nicelhc13 commented
> Object parameters should be `const Type&` if it is passed by value and `Type *` if it is passed by reference.
> 
> If a class is mostly just getters and setters, then it is better as a struct.

I agreed with you but in some cases, it is impossible to attach the `const` keyword due to iterators. For example, I am using a range for loop with a parameter passed as a reference and the compiler complained that the iterators of begin() and end() could not be used with the const keyword. I will explore them more.

2020-09-28 19:21 UTC, roshandathathri commented
> the compiler complained that the iterators of begin() and end() could not be used with the const keyword

This likely means that begin() and end() of that class need to be made const. You may need to go up the usage chain to change functions to const.

2020-09-28 19:21 UTC, l-hoang commented
> > Object parameters should be `const Type&` if it is passed by value and `Type *` if it is passed by reference.
> > If a class is mostly just getters and setters, then it is better as a struct.
> 
> I agreed with you but in some cases, it is impossible to attach the `const` keyword due to iterators. For example, I am using a range for loop with a parameter passed as a reference and the compiler complained that the iterators of begin() and end() could not be used with the const keyword. I will explore them more.

you can add constant iterators to the graph types

2020-09-28 19:26 UTC, nicelhc13 commented
Thank you. Yes that's a good idea. Let me check if that happened only inside of the Galois library and will add the const functions.

2020-09-29 19:29 UTC, nicelhc13 commented on libgalois/include/galois/graphs/HyperGraph.h
> +  galois::CopyableAtomic<NetnumTy> netnum_;
Hi Roshan, [this comment](https://github.com/KatanaGraph/katana/pull/473#discussion_r485025978) requested access modifier. So you want to keep them as public and remove getter/setter. Am I understanding correctly?

2020-09-29 19:36 UTC, roshandathathri commented on libgalois/include/galois/graphs/HyperGraph.h
> +  galois::CopyableAtomic<NetnumTy> netnum_;
Sorry about going back and forth. 

For HyperGraph which is a derived class of LC_CSR_Graph, I think it is better to have additional variables as private members and provide getters/setters to it.

For MetisNode and MetisGraph, I think it is better to have all members as public, i.e., it is better for those classes to be structs instead.

@ddn0 what do you think?

2020-09-29 19:39 UTC, gurbinder533 commented on libgalois/include/galois/graphs/HyperGraph.h
> +  galois::CopyableAtomic<GainTy>& GetNegativeGain() { return negative_gain_; }
Do we need to return the atomic variable here?

2020-09-29 19:40 UTC, gurbinder533 commented on libgalois/include/galois/graphs/HyperGraph.h
> +  inline galois::CopyableAtomic<NetvalTy>& GetNetrand() { return netrand_; }
Ditto. I would say make these return const NetvalTy instead of atomic.

2020-09-29 19:41 UTC, gurbinder533 commented on libgalois/include/galois/graphs/HyperGraph.h
> +  inline bool IsNotAlone() { return not_alone_; }
const.

2020-09-29 19:45 UTC, gurbinder533 commented on lonestar/analytics/cpu/bipart/Bipart.cpp
> +  HyperGraph& graph = *metis_graph.GetHyperGraph();
why not use pointer HyperGraph* here instead of a reference?

2020-09-29 19:46 UTC, gurbinder533 commented on lonestar/analytics/cpu/bipart/Bipart.cpp
> +  HyperGraph& graph = *metis_graph.GetHyperGraph();
Pointer instead of reference?

2020-09-29 19:47 UTC, gurbinder533 commented on lonestar/analytics/cpu/bipart/Coarsening.cpp
> +        HyperGraph& f_graph = *fine_graphs[index];
pointer.

2020-09-29 19:47 UTC, gurbinder533 commented on lonestar/analytics/cpu/bipart/Coarsening.cpp
> +    HyperGraph& c_graph = *coarse_graphs[i];
ditto

2020-09-29 19:48 UTC, gurbinder533 commented on lonestar/analytics/cpu/bipart/Helper.cpp
> +    HyperGraph& graph, const std::string filename,
HyperGraph*

2020-09-29 19:51 UTC, nicelhc13 commented on lonestar/analytics/cpu/bipart/Helper.h
> +void InitGain(HyperGraph& g);
This function is using `getData()` to modify a node value. So I failed to attach `const`.

2020-09-29 19:53 UTC, nicelhc13 commented on lonestar/analytics/cpu/bipart/Bipart.cpp
> +ComputingCut(HyperGraph& g) {
Same with the above. But this function does not require any modifications. Do you want me to add const iteratros, getData() and getEdgeDst() to the LC_CSR_Graph?

2020-09-29 19:58 UTC, roshandathathri commented on libgalois/include/galois/graphs/HyperGraph.h
> +  inline galois::CopyableAtomic<NetvalTy>& GetNetrand() { return netrand_; }
Agreed. If it is returning a const, it's better to return the value rather than the atomic variable.

2020-09-29 19:58 UTC, ddn0 commented on libgalois/include/galois/graphs/HyperGraph.h
> +  galois::CopyableAtomic<NetnumTy> netnum_;
The distinction that I like to draw is whether you expect callers or the class itself to maintain any object invariants. Looking at `MetisNode` it doesn't look like there is any higher level of abstraction than "this is a collection of fields", so I'd lean towards just making it a struct with public fields and expecting callers to maintain any invariants. This saves you the tedium of:

- const correctness: `bool IsNotAlone()` vs `bool IsNotAlone() const`
- Not applicable here, but move assignment variants for fields of aggregates 

because member access automatically gets the semantics you expect.

For something like a HyperGraph, I'd expect there would be some invariants that you need to uphold in order to still be a valid hyper graph, so I'd lean towards private members and public accessors. Though, if we have a lot of accessors on a HyperGraph, I might wonder if we are conflating multiple ideas into one class or if fields should be grouped together as a separate options class or something.

Nits:
- `inline` is somewhat superfluous for methods defined within a class definition.
- `InitCoarsen` can probably be replaced by initializers on fields, e.g., `bool matched{false}; ...`

2020-09-29 20:18 UTC, nicelhc13 commented on lonestar/analytics/cpu/bipart/Bipart.cpp
> +    std::vector<galois::InsertBag<GNode>>& mem_hedges_of_parts,
```
home/hochan/katana.nicelhc13/lonestar/analytics/cpu/bipart/Bipart.cpp:240:30:   required from here
/home/hochan/katana.nicelhc13/libgalois/include/galois/Bag.h:240:39: error: no matching function for call to ‘galois::InsertBag<unsigned int>::Iterator<const unsigned int>::Iterator(const galois::substrat
e::PerThreadStorage<std::pair<galois::InsertBag<unsigned int>::header*, galois::InsertBag<unsigned int>::header*> >*, unsigned int)’
   const_iterator end() const { return const_iterator(&heads, heads.size()); }
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hochan/katana.nicelhc13/libgalois/include/galois/Bag.h:115:5: note: candidate: galois::InsertBag<T, BlockSize>::Iterator<U>::Iterator(galois::substrate::PerThreadStorage<std::pair<galois::InsertBag<
T, BlockSize>::header*, galois::InsertBag<T, BlockSize>::header*> >*, unsigned int) [with U = const unsigned int; T = unsigned int; unsigned int BlockSize = 0] <near match>
     Iterator(
     ^~~~~~~~
```

This modification made this error. I am still looking into it but do you have any clue on this issue?

2020-09-29 23:27 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Bipart.cpp
> +    std::vector<galois::InsertBag<GNode>>& mem_hedges_of_parts,
What is line 240? Are you using `const GNode h : mem_hedges_of_parts[i]`? If you are, try a simpler example first - maybe with explicit begin and end.

2020-09-30 18:19 UTC, nicelhc13 commented on lonestar/analytics/cpu/bipart/Helper.h
> +ParallelPrefixSum(galois::LargeArray<T>& prefix_sum) {
I see. I checked the scan.h::parallel_prefix_sum(). To me, some parts of the pangolin are better than bipart's one. For example, using finer grained blocks and iterating them through do_all() could improve work efficiency compared to on_each() one. However, it accesses more array during bulk prefix and loses some locality. I would like to try "mix" those two implementations if you are fine.

2020-09-30 18:24 UTC, l-hoang commented on lonestar/analytics/cpu/bipart/Helper.h
> +ParallelPrefixSum(galois::LargeArray<T>& prefix_sum) {
i moved that function to a common area in parallel stl

2020-09-30 18:57 UTC, nicelhc13 commented on lonestar/analytics/cpu/bipart/Helper.h
> +ParallelPrefixSum(galois::LargeArray<T>& prefix_sum) {
Thanks. I checked that.

2020-09-30 18:58 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Helper.h
> +ParallelPrefixSum(galois::LargeArray<T>& prefix_sum) {
Yes, please merge into one paralllel prefix sum that is used in all places.

2020-09-30 19:42 UTC, nicelhc13 commented on lonestar/analytics/cpu/bipart/Bipart.cpp
> +    std::vector<galois::InsertBag<GNode>>& mem_hedges_of_parts,
Yes. I am using that statement. I tried begin() and end() both of them. If I change like the above, it uses `const_iterator` which is `Iterator<const T>()`. Then, it calls constructor with a const header, `iterator(const galois::substrate::PerThreadStorage<std::pair<galois::InsertBag<unsigned int>::header*, galois::InsertBag<unsigned int>::header*> >*, int)`. However, `Iterator` does not have the constructor using the first parameter of the const. I don't know why the header pointer suddenly becomes a const pointer type. Do you have any advice on this?

2020-09-30 19:47 UTC, nicelhc13 commented on lonestar/analytics/cpu/bipart/Bipart.cpp
> +          return;
Return as in break from the loop.

2020-09-30 19:51 UTC, nicelhc13 commented on lonestar/analytics/cpu/bipart/Helper.cpp
> +InitNodes(HyperGraph& graph, uint32_t num_hedges) {
It modifies node values.

2020-09-30 19:51 UTC, nicelhc13 commented on lonestar/analytics/cpu/bipart/Helper.cpp
> +    HyperGraph& graph, std::vector<GNode>& nodes, uint32_t end_offset = 0) {
same with the above

2020-09-30 20:14 UTC, nicelhc13 commented on lonestar/analytics/cpu/bipart/Refine.cpp
> +ResetCounter(HyperGraph& g) {
It modifies data.

2020-09-30 20:14 UTC, nicelhc13 commented on lonestar/analytics/cpu/bipart/Refine.cpp
> +ParallelMakingbalance(HyperGraph& g, float tol) {
It also modifies data.

2020-09-30 20:17 UTC, l-hoang commented on lonestar/analytics/cpu/bipart/Refine.cpp
> +ParallelMakingbalance(HyperGraph& g, float tol) {
what roshan is saying is if it modifies data you need to pass it in as a pointer as that's what katana convention is

2020-09-30 20:18 UTC, nicelhc13 commented on libgalois/include/galois/graphs/HyperGraph.h
> +  galois::CopyableAtomic<GainTy>& GetNegativeGain() { return negative_gain_; }
To my best knowledge, it is necessary. It is used as parameters for atomic operations.

2020-09-30 20:19 UTC, nicelhc13 commented on libgalois/include/galois/graphs/HyperGraph.h
> +  inline galois::CopyableAtomic<NetvalTy>& GetNetrand() { return netrand_; }
Same with the above. The return is directly used by atomic operation. What do you think?

2020-10-01 19:00 UTC, ddn0 commented
BTW, some of the review suggestions are things that are automatically reported by clang-tidy, and most editors can be configured to report these as warnings continuously if you want to reduce the number of rounds of review and save your reviewer's attention for less superficial aspects.

2020-10-05 16:03 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Helper.cpp
> +InitNodes(HyperGraph& graph, uint32_t num_hedges) {
Then `HyperGraph*`

2020-10-05 16:03 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Helper.cpp
> +    HyperGraph& graph, std::vector<GNode>& nodes, uint32_t end_offset = 0) {
Then `HyperGraph*`

2020-10-05 16:04 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Refine.cpp
> +ResetCounter(HyperGraph& g) {
Then `HyperGraph*`

2020-10-05 16:04 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Refine.cpp
> +ParallelMakingbalance(HyperGraph& g, float tol) {
Then `HyperGraph*`

2020-10-07 21:59 UTC, uditagar commented on libgalois/include/galois/graphs/HyperGraph.h
> +  galois::CopyableAtomic<GainTy>& GetNegativeGain() { return negative_gain_; }
I think Gill is right here. We can just return GainTy type, since we are not using it for any atomic operations. The atomic operations are happening in the perThread vector (or global vectors). The node's gain values are updated only via setGain functions.

2020-10-07 22:02 UTC, uditagar commented on libgalois/include/galois/graphs/HyperGraph.h
> +  inline galois::CopyableAtomic<NetvalTy>& GetNetrand() { return netrand_; }
Hochan is right here. GetNetrand is used in atomic operation

2020-10-07 23:27 UTC, gurbinder533 commented on libgalois/include/galois/graphs/HyperGraph.h
> +  galois::CopyableAtomic<GainTy>& GetNegativeGain() { return negative_gain_; }
Get function should not be modifying anything. Have a corresponding "Set" function for that.

2020-10-07 23:34 UTC, uditagar commented on libgalois/include/galois/graphs/HyperGraph.h
> +  galois::CopyableAtomic<GainTy>& GetNegativeGain() { return negative_gain_; }
Yes, this get function is not modifying anything. It's only used for accessing the gain value.

2020-10-08 17:41 UTC, nicelhc13 commented on lonestar/analytics/cpu/bipart/Bipart.cpp
> +ComputingCut(HyperGraph& g) {
Replaced it with pointer type.

2020-10-08 17:41 UTC, nicelhc13 commented on lonestar/analytics/cpu/bipart/Bipart.cpp
> +    std::vector<galois::InsertBag<GNode>>& mem_hedges_of_parts,
Fixed it by implementing const iterator execution pass.

2020-10-08 21:41 UTC, nicelhc13 commented on libgalois/include/galois/graphs/HyperGraph.h
> +  galois::CopyableAtomic<GainTy>& GetNegativeGain() { return negative_gain_; }
Oh, you guys are right. In this case, we can return GainTy. Thank you for pointing this out.

2020-10-09 17:37 UTC, ddn0 commented on libgalois/include/galois/Bag.h
> +    const galois::substrate::PerThreadStorage<std::pair<header*, header*>>*
This is the basic idea for const support but we want to do it without adding another field and bloating the representation (and the code to maintain).

How about we promote the idea `is_const` to the level of metaprogramming rather than as a value, e.g.,

```cpp
class Iterator .... {
  using Storage = galois::substrate::PerThreadStorage<std::pair<header*, header*>>;
  using Head = std::conditional_t<std::is_const_v<U>, const Storage*, Storage*>;
  Head hd;

  ....
};
```

The rest of the code should be the same as before (I think).

2020-10-09 17:37 UTC, ddn0 commented on libgalois/include/galois/graphs/HyperGraph.h
> +struct MetisNode {
why is this Metis specific stuff in libgalois?

2020-10-09 17:37 UTC, ddn0 commented on libgalois/include/galois/graphs/LC_CSR_Graph.h
> +  const_edge_iterator const_raw_begin(GraphNode N) const {
why not just call this `const_edge_iterator raw_begin(GraphNode N) const`?

2020-10-10 03:10 UTC, nicelhc13 commented on libgalois/include/galois/graphs/HyperGraph.h
> +struct MetisNode {
I moved this from Bipart to here in order to reflect [this ](https://github.com/KatanaGraph/katana/pull/473#discussion_r485025691)@roshandathathri 's comment. The `HyperGraph` needs the `MetisNode`. Could you suggest better ways for this?

2020-10-10 03:30 UTC, nicelhc13 commented on libgalois/include/galois/graphs/LC_CSR_Graph.h
> +  const_edge_iterator const_raw_begin(GraphNode N) const {
To the best of my knowledge, it cannot be due to this standard:

> (3.4) — Parameter declarations that differ only in the presence or absence of const and/or volatile are equivalent. That is, the const and volatile type-specifiers for each parameter type are ignored when determining which function is being declared, defined, or called.

I tried it but got the below error:

```
/home/hochan/katana.nicelhc13/libgalois/include/galois/graphs/LC_CSR_Graph.h:183:23: error: ‘galois::graphs::LC_CSR_Graph<NodeTy, EdgeTy, HasNoLockable, UseNumaAlloc, HasOutOfLineLockable, FileEdgeTy>::const_edge_iterator galois::graphs::LC_CSR_Graph<NodeTy, EdgeTy, HasNoLockable, UseNumaAlloc, HasOutOfLineLockable, FileEdgeTy>::raw_begin(galois::graphs::LC_CSR_Graph<NodeTy, EdgeTy, HasNoLockable, UseNuma
Alloc, HasOutOfLineLockable, FileEdgeTy>::GraphNode) const’ cannot be overloaded                  
   const_edge_iterator raw_begin(GraphNode N) const {  
```

Could you give any instruction on this?

2020-10-10 15:09 UTC, ddn0 commented on libgalois/include/galois/graphs/HyperGraph.h
> +struct MetisNode {
Presumably in the same way we can define an LC_Graph without having the node data for SSSP, BFS, etc also defined in the same class as LC_Graph.

2020-10-10 15:12 UTC, ddn0 commented on libgalois/include/galois/graphs/LC_CSR_Graph.h
> +  const_edge_iterator const_raw_begin(GraphNode N) const {
declare both:
```cpp
const_edge_iterator raw_begin(GraphNode N) const
edge_iterator raw_begin(GraphNode N)
```

2020-10-10 19:51 UTC, nicelhc13 commented on libgalois/include/galois/graphs/LC_CSR_Graph.h
> +  const_edge_iterator const_raw_begin(GraphNode N) const {
You are right. If I declare `const HyperGraph` then the iterator also became `const`. Thank you for pointing this out.

2020-10-10 19:54 UTC, nicelhc13 commented on libgalois/include/galois/graphs/HyperGraph.h
> +struct MetisNode {
Yes you are also right. I misunderstood that the `HyperGraph` is tightly connected with `MetisNode`. Thank you for pointing this out. I will fix it.

2020-10-14 19:21 UTC, roshandathathri approved these changes
LGTM

Minor nits below

2020-10-14 19:21 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Bipart.cpp
> +      for (GNode n = num_hedges; n < static_cast<uint32_t>(g.size()); n++) {
`static_cast<GNode>`

2020-10-14 19:21 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Bipart.cpp
> + */
Add comments or delete these 3 lines

2020-10-14 19:21 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Bipart.cpp
> + */
Ditto

2020-10-14 19:21 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Bipart.cpp
> + */
Ditto

2020-10-14 19:21 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Bipart.cpp
> + */
Ditto

2020-10-14 19:21 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Bipart.cpp
> + */
Ditto

2020-10-14 19:21 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Coarsening.cpp
> +        MetisGraph*& graph = metis_graphs->at(i);
Avoid `*&`

2020-10-14 19:21 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Coarsening.cpp
> +      MetisGraph*& graph = metis_graphs->at(i);
Ditto

2020-10-14 19:21 UTC, roshandathathri commented on lonestar/analytics/cpu/bipart/Coarsening.cpp
> +      MetisGraph*& graph = metis_graphs->at(i);
Ditto

2020-10-14 19:22 UTC, roshandathathri commented
Please rebase on master. That will fix the CI build failures.

2020-10-14 22:04 UTC, nicelhc13 commented on libgalois/include/galois/Bag.h
> +        std::conditional_t<std::is_const_v<U>, const Storage*, Storage*>;
Good point. Thank you. I will replace them.

2020-10-14 22:08 UTC, nicelhc13 commented on lonestar/analytics/cpu/bipart/Bipart.cpp
> + */
@uditagar Udit, do you want to put comment on these line? For the future I added them but if you don't have anything then I could remove them. Below comments are same. Thank you

2020-10-14 22:17 UTC, uditagar commented on lonestar/analytics/cpu/bipart/Bipart.cpp
> + */
yes, I can do that.

2020-10-15 00:37 UTC, uditagar commented on lonestar/analytics/cpu/bipart/Bipart.cpp
> + */
for this:
/** Assigns a partition to each hyperedge based on the current partitioning assignment of the nodes
 * @param graph Graph
 * @param num_hedges Number of hyperedges in the specified param graph
 */

2020-10-15 00:43 UTC, nicelhc13 commented on lonestar/analytics/cpu/bipart/Partitioning.cpp
> +    const std::vector<unsigned>& K) {
@uditagar  how about target_partitions?

2020-10-15 00:46 UTC, uditagar commented on lonestar/analytics/cpu/bipart/Bipart.cpp
> + */
for this:
/** Assigns an id to the nodes and hyperedges in each child partition
 * 
 * @param current_level_indices Set containing indexes of current child partitions
 * @param mem_nodes_of_parts Vector of InsertBags containing nodes for each child partition
 * @param mem_hedges_of_parts Vector of InsertBags containing hyperedges for each child partition
 * @param hnodes_bag InsertBag of pair of the partition index and the node's child id, for each node
 * @param hedges_bag InsertBag of pair of the partition index and the hyperedges's child id, for each node
 * @param graph Graph
 */

2020-10-15 00:48 UTC, uditagar commented on lonestar/analytics/cpu/bipart/Partitioning.cpp
> +    const std::vector<unsigned>& K) {
yes, that's good.

2020-10-15 02:53 UTC, nicelhc13 commented
Thank you for reviewing this PR. It has been reviewed for a long time. Please finalize your review. I reflected all of your comments. This codes left tasks of 1) using proper vector types among `galois::gstl::Vector`, `std::vector`, and `galois::LargeArray`, and 2) better documentations. Since this PR is already very long sufficiently, I will left those works as the next PR. Thank you.

2020-10-15 02:56 UTC, uditagar approved these changes
Looks good.

2020-10-15 03:01 UTC, roshandathathri commented
> Since this PR is already very long sufficiently, I will left those works as the next PR.

Yes, I have already approved. Please merge when the tests pass.

2020-10-15 19:35 UTC, merged