Use Arrow type system directly, Support Date-Time
KatanaGraph/katana pull request #540
Opened 2020-10-07 21:09 UTC by danielmawhirter

This PR should remove Type-identification enums in favor of directly using Arrow's type system. The purpose of this change is to generally simplify the future addition of more types, and specifically to add Date-Time support.

2020-10-07 21:15 UTC, danielmawhirter commented on libquery/src/Column.cpp
> +}
This template appears in both Table.cpp and Column.cpp inside an anonymous namespace. Due to the specialization, it was the only way I found to avoid compiler/linker errors. If you have a better idea, let me know.

2020-10-07 22:08 UTC, danielmawhirter commented on libquery/test/filter-op-test.cpp
> +#define HERE fprintf(stderr, "HERE at %s:%d\n", __FILE__, __LINE__)
These will be going away, they were a debugging tool that shouldn't have made it into the commit

2020-10-07 22:40 UTC, danielmawhirter commented on libquery/src/PropertyFunc.cpp
> +  } else if (col.HasMeta("IsEdge")) {
New checking that a column represents a Vertex or Edge

2020-10-07 22:41 UTC, danielmawhirter commented on libquery/src/Table.cpp
> +        node_names[i].name, arrow::int32(), {{"IsVertex", "true"}}, array);
Setting IsVertex on vertices

2020-10-07 22:41 UTC, danielmawhirter commented on libquery/src/Table.cpp
> +    Column col(edge_names[i].name, arrow::int64(), {{"IsEdge", "true"}}, array);
Setting IsEdge on edges

2020-10-08 02:09 UTC, danielmawhirter reviewed
Summary:

2020-10-08 02:09 UTC, danielmawhirter commented on libquery/include/querying/Column.h
> -};
Everything else in this PR stems from this removal

2020-10-08 02:09 UTC, danielmawhirter commented on libquery/include/querying/Column.h
> +  Array array_;
Column now owns an arrow::Array and all associated metadata

2020-10-08 02:09 UTC, danielmawhirter commented on libquery/include/querying/Table.h
> +  std::vector<galois::Column> columns_;
A Table is now just an ordered collection of columns. The only reason not to flatten it further into arrow::Table is that structure uses ChunkedArray, which I am avoiding

2020-10-08 16:56 UTC, danielmawhirter commented
Ready to merge, needs review

2020-10-08 17:22 UTC, bowu requested changes

2020-10-08 17:22 UTC, bowu commented on libquery/src/Expression.cpp
> +  fprintf(stderr, "right: %s\n", right.GetData()->ToString().c_str());
Delete?

2020-10-08 17:22 UTC, bowu commented on libquery/src/GroupByOp.cpp
> +  SetOutput(builder.Make());*/
Do some cleaning and delete all unneeded code.

2020-10-08 17:22 UTC, bowu commented on libquery/src/LimitOp.cpp
> +  if (table) {
I was just wondering when the new implementation of Table could have trouble, but overall it should be better.

2020-10-08 17:22 UTC, bowu commented on libquery/src/PropertyFunc.cpp
> +    fprintf(stderr, "Properties:\n%s\n", col.PropertiesString().c_str());
Avoid using fprintf.

2020-10-08 17:22 UTC, bowu commented on libquery/src/LimitOp.cpp
> +  if (table) {
Wrap this part as a member function of Table. It's just Slice.

2020-10-08 17:22 UTC, bowu commented on libquery/src/SkipOp.cpp
> +  if (table) {
Wrap this part as a member function of Table.

2020-10-08 17:22 UTC, bowu commented on libquery/test/filter-op-test.cpp
> +  /*AddFilterOp(fmt::format("match (a) where num1 = 6 return a;"), &filters);
Why commented out?

2020-10-08 17:33 UTC, ddn0 reviewed
Looking good.

I have mostly style comments. My main substantive question is whether we should create some constants for the metadata keys.

2020-10-08 17:33 UTC, ddn0 commented on libquery/include/querying/Table.h
> +  std::vector<galois::Column> columns_;
perhaps doxygen comment on the `galois::Column` class with this bit of reasoning? E.g.,
```
/// A Table ....
///
/// A Table differs from an arrow::Table in that it requires all columns to be arrow::Arrays rather than
/// arrow::ChunkedArrays. It also provides more convenient access to metadata like .....
class Column { ... };
```

2020-10-08 17:33 UTC, ddn0 commented on libquery/include/querying/Table.h
> +/*class Table::Builder {
delete delete delete

2020-10-08 17:33 UTC, ddn0 commented on libquery/src/Column.cpp
> +}
you could have an internal header file that is in `src`, but I think what you have is fine for now. If someone wants this pattern for a third time, we can revisit.

2020-10-08 17:33 UTC, ddn0 commented on libquery/src/Expression.cpp
> +  fprintf(stderr, "left: %s\n", left.GetData()->ToString().c_str());
This seems like debugging code?

Anyway, let's avoid C-style output functions. We already have `std::cout`, `GALOIS_LOG_` and `fmt`.

2020-10-08 17:33 UTC, ddn0 commented on libquery/src/GroupByOp.cpp
> +  //Table::Schema schema;
delete delete delete

2020-10-08 17:33 UTC, ddn0 commented on libquery/src/LimitOp.cpp
> +  if (table) {
small style nit:

```cpp
if (!table) {
  SetOutput(nullptr);
  return PropagateOutput();
}
....
```

I think the small pain in repeating some code is worth establishing the invariant "after this point in the code table is valid"/"don't worry I've handled the !table case, rest easy".

2020-10-08 17:33 UTC, ddn0 commented on libquery/src/PropertyFunc.cpp
> +    fprintf(stderr, "Properties:\n%s\n", col.PropertiesString().c_str());
debug code?

2020-10-08 17:33 UTC, ddn0 commented on libquery/src/PropertyFunc.cpp
> +  if (col.HasMeta("IsVertex")) {
probably should start establishing reserved names/constants for metadata?

in the RDG files we have been using this form: `kg.v1.stuff`

2020-10-08 17:33 UTC, ddn0 commented on libquery/src/SkipOp.cpp
> +  if (table) {
ditto

2020-10-08 17:33 UTC, ddn0 commented on libquery/src/Table.cpp
> +/*template <typename T>
delete delete delete

2020-10-08 17:33 UTC, ddn0 commented on libquery/test/filter-op-test.cpp
> +  /*AddFilterOp(fmt::format("match (a) where num1 = 6 return a;"), &filters);
if this needs to be disabled temporarily and it still compiles, I'd leave the code but just add a branch that is never taken + a todo comment explaining why these tests are skipped.

2020-10-08 17:33 UTC, ddn0 commented on libquery/test/table-bench.cpp
> +  /*std::shared_ptr<arrow::Table> input_table = arrow::Table::Make(
delete?

2020-10-08 17:33 UTC, ddn0 commented on scripts/json_checker.py
> +          print('expected:', json.dumps(truth, sort_keys=True, indent=2))
don't know if this would be super useful, but perhaps running the output through difflib or similar https://docs.python.org/3/library/difflib.html might help people see errors faster.

2020-10-08 17:45 UTC, danielmawhirter commented on libquery/test/filter-op-test.cpp
> +  /*AddFilterOp(fmt::format("match (a) where num1 = 6 return a;"), &filters);
oops

2020-10-08 17:47 UTC, danielmawhirter commented on libquery/include/querying/ArrowTypes.h
> +ArrowUntemplate(std::shared_ptr<arrow::DataType> dtype, Args&&... args) {
That sounds better

2020-10-08 17:55 UTC, danielmawhirter commented on libquery/include/querying/Column.h
> +  const MetaData GetMeta() const { return meta_; }
Going with GetAlias, SetAlias

2020-10-08 18:00 UTC, danielmawhirter commented on libquery/include/querying/Column.h
> +    return Column("NoName", type, nullptr, array);
Column names are expected to be unique within a table, but bare columns have no restriction. This should never make it into output, but "" didn't seem right either. Maybe call it Repeat so if it ever shows up, its origin is known?

2020-10-08 18:09 UTC, danielmawhirter commented on scripts/json_checker.py
> +          print('expected:', json.dumps(truth, sort_keys=True, indent=2))
Will look into it

2020-10-08 18:09 UTC, danielmawhirter commented on libquery/test/filter-op-test.cpp
> +  /*AddFilterOp(fmt::format("match (a) where num1 = 6 return a;"), &filters);
oops

2020-10-08 19:00 UTC, ddn0 commented on libquery/include/querying/Column.h
> +    return Column("NoName", type, nullptr, array);
I think at the very least define a constant for this so we know it is special.

2020-10-08 23:38 UTC, roshandathathri approved these changes
LGTM

Minor nits below

Please make sure that the full-table tests pass (at least on your machine if the CI tests are disabled)

2020-10-08 23:38 UTC, roshandathathri commented on libquery/include/querying/ArrowTypes.h
> +// This function requires at least c++14 support
Can be dropped as we required compilers with that support already.

2020-10-08 23:38 UTC, roshandathathri commented on libquery/include/querying/Column.h
> +  using DataType = std::shared_ptr<arrow::DataType>;
Coding convention is public first, then protected, and then private. You don't have to fix it for previous code but please apply it for new code.

2020-10-08 23:38 UTC, roshandathathri commented on libquery/include/querying/Table.h
> +//! Differs from arrow::Table in that Columns are arrow::Array rather
Does it make sense to move arrow wrappers out of libquery into libgalois or some other lib? Need not be in this PR.

@ddn0

2020-10-08 23:38 UTC, roshandathathri commented on libquery/src/GroupByOp.cpp
> +    //    size_t accum = 0;
Better to delete unused code. 

If you want to keep it around, move it into a different function and don't call it.

2020-10-08 23:38 UTC, roshandathathri commented on libquery/src/PropertyFunc.cpp
> +  if (col.HasMeta("kg.IsVertex")) {
Is "kg.Is" required? Isn't "Vertex" sufficient?

2020-10-08 23:38 UTC, roshandathathri commented on libquery/src/PropertyFunc.cpp
> +  } else if (col.HasMeta("kg.IsEdge")) {
Isn't "Edge" sufficient?

2020-10-08 23:38 UTC, roshandathathri commented on libquery/test/filter-op-test.cpp
> +#define HERE fprintf(stderr, "HERE at %s:%d\n", __FILE__, __LINE__)
Why is this required? GALOIS_LOG_* already provides these features right?

2020-10-08 23:38 UTC, roshandathathri commented on libquery/src/Expression.cpp
> +  static const std::unordered_map<galois::ExpressionOperator, std::string>
static const vs. switch case (preferably in a separate function)? I prefer the latter. I'm not sure of the trade-offs. 

I didn't suggest this for CYPHER_OP_* because if I remember right, that requires if-else and doesn't work with switch-case. 

@ddn0

2020-10-08 23:38 UTC, roshandathathri commented on libquery/src/Expression.cpp
> +  static const std::unordered_map<galois::ExpressionOperator, std::string>
Ditto

2020-10-09 00:37 UTC, danielmawhirter commented on libquery/test/filter-op-test.cpp
> +#define HERE fprintf(stderr, "HERE at %s:%d\n", __FILE__, __LINE__)
Sorry, that's debugging stuff slipping through again

2020-10-09 00:39 UTC, danielmawhirter commented on libquery/src/GroupByOp.cpp
> +    //    size_t accum = 0;
It's part of the functionality of this particular function, but it doesn't work due to a concern with variant that Bo and I are working on. So the code isn't unused, it's disabled for now. If you still think I should delete it let me know

2020-10-09 00:41 UTC, danielmawhirter commented on libquery/include/querying/Table.h
> +//! Differs from arrow::Table in that Columns are arrow::Array rather
IMO yes, but long term, I expect Scalar, Column, and Table will probably disappear altogether, and be replaced with simple collections of convenience functions for Arrow.

2020-10-09 00:43 UTC, danielmawhirter commented on libquery/include/querying/ArrowTypes.h
> +// This function requires at least c++14 support
I wrote that because, if I were to come along and try to understand this function, it would be helpful to know what standard this nested template structure showed up in, since post c++11 isn't really the norm yet most places. If you think the weirdness outweighs the benefit, I'll remove it

2020-10-09 00:44 UTC, ddn0 commented on libquery/src/PropertyFunc.cpp
> +  if (col.HasMeta("kg.IsVertex")) {
I mentioned this under the assumption that users might introduce their own metadata in order to distinguish our metadata from theirs. If that is not possible, "Vertex" is fine, though I still think these should be constants somewhere.

2020-10-09 00:46 UTC, danielmawhirter commented on libquery/src/PropertyFunc.cpp
> +  if (col.HasMeta("kg.IsVertex")) {
None of this is required, it could be "1234", but see https://github.com/KatanaGraph/katana/pull/540#discussion_r501887880 for thoughts on standardizing

2020-10-09 00:50 UTC, danielmawhirter commented on libquery/src/Expression.cpp
> +  static const std::unordered_map<galois::ExpressionOperator, std::string>
switch/case, as implemented, was requiring things like Equals to be defined two places, for string and numeric. With types like DateTime coming, I'd rather encapsulate it so we don't have to do it 3 places. The capability to use a function on particular types flows from Arrow's capabilities. And if we need more than it offers, we'll eventually register more kernels. I suppose this function could become switch-case if that's strongly preferred

2020-10-09 00:52 UTC, danielmawhirter commented on libquery/src/Expression.cpp
> +  static const std::unordered_map<galois::ExpressionOperator, std::string>
This felt like something that should naturally match what's happening in Expression.
I converted this, in part, to highlight that we have several steps between cypher commands and arrow commands, that may simply be over-abstracting for cases like this that are nearly one-to-one

2020-10-09 02:27 UTC, ddn0 commented on libquery/src/Expression.cpp
> +  static const std::unordered_map<galois::ExpressionOperator, std::string>
Probably the strongest (maintainability) argument for switch would be if ExpressionOperator were an `enum class` (which it is not currently), it is pretty common for compilers to give you a helpful warning if you are missing a case statement.

If there is a different pattern that would still give us equivalent maintainability or if you plan to change this I wouldn't bother too much.

If this were performance critical, there would be some more arguments to switch-case over map but I don't think that is applicable at the moment.

BTW: `const std::vector<arrow::Datum>&`

2020-10-09 15:39 UTC, danielmawhirter commented on libquery/src/Expression.cpp
> +  static const std::unordered_map<galois::ExpressionOperator, std::string>
It is an enum class in these changes

2020-10-09 16:03 UTC, ddn0 commented on libquery/include/querying/ArrowTypes.h
> +// This function requires at least c++14 support
If you are going to leave a comment, it probably should be a little more specific about what features are required.

Is it just more deduction contexts for `auto` https://godbolt.org/z/Px6GWr ? If so, I wouldn't think that is weird just a little better than what C++11 supports.

Anyway, if the purpose is educating the reader a link or more text would be nice. If the purpose is to guard against using an unsupported compiler, an `ifdef` or something machine-interpretable would be better (and totally unnecessary in this case). In both cases, we should be mindful of the fact that we already require at least C++17 support.

2020-10-09 18:43 UTC, ddn0 commented on libquery/src/Column.cpp
> +const std::string galois::Column::VERTEX_IDENTIFIER = "kg.VERTEX";
kVertexIdentifier....

2020-10-09 20:47 UTC, danielmawhirter commented
@bowu Do my changes satisfy your change request?

2020-10-09 21:44 UTC, roshandathathri approved these changes
Minor fixes below

2020-10-10 01:02 UTC, bowu reviewed
The change looks good to me.

2020-10-10 03:29 UTC, bowu approved these changes

2020-10-10 23:27 UTC, merged