Partial DateTime Support
KatanaGraph/katana pull request #556
Opened 2020-10-14 22:16 UTC by danielmawhirter

This should be PR 2/3 for adding DateTime support.
OrderBy fully supports the DateTime types
Improved Visitor interface for arrow Arrays in operators

2020-10-15 16:44 UTC, bowu requested changes
LGTM

2020-10-15 16:44 UTC, bowu commented on libquery/src/OrderByOp.cpp
> +struct SortIndicesByColumn {
This is nice! Since we support full-table comparison now, can you add more tests for order by?

2020-10-15 16:44 UTC, bowu commented on libquery/src/Table.cpp
> +      GALOIS_LOG_FATAL("Unexpected arrow::Type for a DateTime");
I'll merge PR#550 (https://github.com/KatanaGraph/katana/pull/550) soon. Please return an error code instead of aborting the process. For example: https://github.com/bowu/katana/blob/error_code/libquery/src/FilterOp.cpp#L18

2020-10-15 16:44 UTC, bowu commented on libquery/src/Table.cpp
>    GALOIS_LOG_FATAL("NAME MISMATCH");
ditto

2020-10-15 17:18 UTC, danielmawhirter commented on libquery/src/OrderByOp.cpp
> +struct SortIndicesByColumn {
I'll be adding quite a few tests once DateTime as a whole works, so absolutely!

2020-10-15 17:19 UTC, danielmawhirter commented on libquery/src/Table.cpp
> +      GALOIS_LOG_FATAL("Unexpected arrow::Type for a DateTime");
I'll be able to once that PR lands, as the error codes aren't in kg/master yet

2020-10-15 20:48 UTC, ddn0 reviewed
mostly C++ style nits.

Looking forward to seeing this merged!

2020-10-15 20:48 UTC, ddn0 commented on libquery/include/querying/ArrowTypes.h
> +  static inline const std::shared_ptr<Array> View(const arrow::Array& array) {
A little const cleanup in this section
```diff
diff --git a/libquery/include/querying/ArrowTypes.h b/libquery/include/querying/ArrowTypes.h
index 319689e7b..29e9a9896 100644
--- a/libquery/include/querying/ArrowTypes.h
+++ b/libquery/include/querying/ArrowTypes.h
@@ -16,7 +16,7 @@ struct ArrowTypes {
   static const std::shared_ptr<arrow::DataType> DataType;
 
   static inline Builder& Specialize(
-      std::unique_ptr<arrow::ArrayBuilder>& builder) {
+      const std::unique_ptr<arrow::ArrayBuilder>& builder) {
     return *(dynamic_cast<Builder*>(builder.get()));
   }
 
@@ -24,19 +24,19 @@ struct ArrowTypes {
     return dynamic_cast<const Array&>(array);
   }
 
-  static inline const std::shared_ptr<Array> Specialize(
+  static inline std::shared_ptr<Array> Specialize(
       const std::shared_ptr<arrow::Array>& array) {
     return std::dynamic_pointer_cast<Array>(array);
   }
 
-  static inline const std::shared_ptr<Array> View(const arrow::Array& array) {
+  static inline std::shared_ptr<Array> View(const arrow::Array& array) {
     const auto res = array.View(DataType);
     GALOIS_LOG_VASSERT(res.ok(), "view error: {}", res.status());
-    const std::shared_ptr<arrow::Array> prim_view = res.ValueOrDie();
+    const std::shared_ptr<arrow::Array>& prim_view = res.ValueOrDie();
     return Specialize(prim_view);
   }
 
-  static inline const std::shared_ptr<Array> View(
+  static inline std::shared_ptr<Array> View(
       const std::shared_ptr<arrow::Array>& array) {
     return View(*(array.get()));
   }
```

2020-10-15 20:48 UTC, ddn0 commented on libquery/include/querying/Table.h
> +  //nlohmann::json ToJSON() const;
Why is this not needed anymore? And probably just delete this declaration.

2020-10-15 20:48 UTC, ddn0 commented on libquery/src/ArrowArrays.h
> +[[maybe_unused]] std::string
It is probably more consistent with other header files to just add `inline` to both the template specializations (`template <>`) rather than add `[[maybe_unused]]`. The current code is correct now because it is in a unnamed namespace, but by adding `inline` it will work even without `namespace { .... }`.

2020-10-15 20:48 UTC, ddn0 commented on libquery/src/Column.cpp
>  }
Re:
```
const std::string galois::Column::kVERTEX_IDENTIFIER = "kg.VERTEX";
const std::string galois::Column::kEDGE_IDENTIFIER = "kg.EDGE";
```

these constants should be named `kEdgeIdentifier`, etc.

2020-10-15 20:48 UTC, ddn0 commented on libquery/src/Column.cpp
> +    return Call<T>(*(view.get()));
`*view.get()` => `*view`

2020-10-15 20:48 UTC, ddn0 commented on libquery/src/Column.cpp
> +  GALOIS_LOG_ASSERT(result.ok());
ideally, `std::shared_ptr<arrow::Scalar> scalar = result.ValueOrDie();` would be written `std::shared_ptr<arrow::Scalar> scalar = std::move(result.ValueOrDie());` otherwise we make an unnecessary copy of result, which for pointers is okay, but for shared_ptrs, this is an atomic increment, which is also probably okay, but the rest of the codebase is quite good about avoiding copying results, so we might as well continue the tradition.

2020-10-15 20:48 UTC, ddn0 commented on libquery/src/CypherCompiler.cpp
> +      if (!res)
nit: keep the braces for the if statement.

2020-10-15 20:48 UTC, ddn0 commented on libquery/src/CypherCompiler.cpp
> +  if (res) {
should we propagate an error if `ParseOrderByNode` returns an error?

2020-10-15 20:48 UTC, ddn0 commented on libquery/src/GroupByOp.cpp
> +    if (!res)
nit: if braces

ditto: move results

2020-10-15 20:48 UTC, ddn0 commented on libquery/src/Table.cpp
> +  galois::Result<void> ok;
`ok_`?

2020-10-15 20:48 UTC, ddn0 commented on libquery/src/Table.cpp
> +  AssignJSONValue(int64_t index, std::string key, nlohmann::json* json_object)
nit: some newlines between declarations would help me

2020-10-15 20:48 UTC, ddn0 commented on libquery/src/Table.cpp
> +  AssignJSONValue(int64_t index, std::string key, nlohmann::json* json_object)
`const std::string& key` or `.... : key_(std::move(key))`

2020-10-15 20:48 UTC, ddn0 commented on libquery/src/Table.cpp
> +    return ArrowArrayGetValue<T>(*(typed.get()), index);
`*typed`

2020-10-15 20:48 UTC, ddn0 commented on libquery/src/Table.cpp
> +  const auto typed = ArrowTypes<T>::Specialize(array);
`const` doesn't seem necessary FWIW.

2020-10-15 20:48 UTC, ddn0 commented on libquery/src/Table.cpp
> +    os << dump.value() << std::endl;
probably just `"\n"`

2020-10-15 20:48 UTC, ddn0 commented on libquery/src/Table.cpp
> +    if (!os.good()) {
just `if (!os) { .... }`; it's more idiomatic and is correct in more situations.

2020-10-15 20:48 UTC, ddn0 commented on libquery/src/Table.cpp
> +      auto data = ArrowArrayGetValue<std::string>(*(array.get()), row_ind);
`*array` throughout.

2020-10-15 20:48 UTC, ddn0 commented on lonestar/querying/distributed/graph-query/graph-query.cpp
> +          auto res = table->OutputJSON(json_file);
if you want:
```cpp
if (auto res ...; !res) {

}
```

2020-10-15 21:11 UTC, danielmawhirter commented on libquery/src/Table.cpp
> +#include <arrow/vendored/datetime/date.h>
This library is being rolled into c++20. Due to the namespaces, inter-op should be just fine. The option of always using the vendor copy should also be fine. IMO arrow's version is nice just for packaging reasons, since the library explicitly states that cmake support isn't really a design goal.

2020-10-15 21:15 UTC, danielmawhirter commented on libquery/include/querying/Table.h
> +  //nlohmann::json ToJSON() const;
The old version is high-memory (builds the table as an array of json objects before serializing), the new version is stream-oriented (builds one row at a time before serializing). The new version also matches neo4j's style better

2020-10-15 21:19 UTC, danielmawhirter commented on libquery/src/CypherCompiler.cpp
> +  if (res) {
The old version had 3 output possibilities 1) success, non-null 2) return nullptr 3) crash
I combined 2 and 3, I guess I should be keeping all of these

2020-10-15 21:22 UTC, danielmawhirter commented on libquery/include/querying/ArrowTypes.h
> +  static inline const std::shared_ptr<Array> View(const arrow::Array& array) {
All of these are based on my mistaken understanding that an object referred to by a const shared_ptr is effectively const, cleaning it up, thanks

2020-10-16 17:14 UTC, danielmawhirter commented
@bowu Ready to merge?

2020-10-16 17:40 UTC, ddn0 approved these changes
:balloon:

2020-10-16 18:04 UTC, roshandathathri approved these changes
LGTM

2020-10-16 18:04 UTC, roshandathathri commented on libquery/src/OrderByOp.cpp
> +      const DateTimeArrayType& array, [[maybe_unused]] arrow::Type::type type) {
If it is definitely not used, you can drop both `[[maybe_unused]]` and the variable name `type`

2020-10-16 18:04 UTC, roshandathathri commented on libquery/src/Table.cpp
> +        key_(key),
Intentional copy of string?

2020-10-16 18:18 UTC, ddn0 commented on libquery/include/querying/ArrowTypes.h
> +#ifndef NDEBUG
I asked for an assertion to be added.

Dynamic casts can fail: https://en.cppreference.com/w/cpp/language/dynamic_cast it seems reasonable to check for this at least sometimes rather than invite unsafe memory accesses.

I would also be okay with:

```cpp
assert(ptr);
```

2020-10-16 18:26 UTC, danielmawhirter commented on libquery/include/querying/ArrowTypes.h
> +    return visitor.template CallDateTime<int32_t, arrow_vendored::date::days>(
Yes. In addition to a c++ type, they have a unit, an epoch, and (later maybe) a timezone. Sometimes they can be treated as just a c++ types, as in OrderBy, but not always, like in OutputJson

2020-10-16 18:28 UTC, danielmawhirter commented on libquery/src/Column.cpp
> +        std::is_same<T, typename DateTimeArrayType::value_type>::value);
Yes, but I want to make sure that the templates match up. A change like that will likely come at some point in the future, in terms of general philosophy, but for now I'd rather validate the assumption.

2020-10-16 18:33 UTC, danielmawhirter commented on libquery/src/OrderByOp.cpp
> +      const DateTimeArrayType& array, [[maybe_unused]] arrow::Type::type type) {
Nice, didn't know that worked

2020-10-16 18:33 UTC, danielmawhirter commented on libquery/src/Table.cpp
> +        key_(key),
fixed

2020-10-16 18:37 UTC, roshandathathri commented on libquery/include/querying/ArrowTypes.h
> +    return visitor.template CallDateTime<int32_t, arrow_vendored::date::days>(
Ok, thanks.

2020-10-16 18:38 UTC, roshandathathri commented on libquery/src/Column.cpp
> +        std::is_same<T, typename DateTimeArrayType::value_type>::value);
Are you saying `T` need not be `value_type` in the future?

2020-10-16 18:40 UTC, danielmawhirter commented on libquery/src/Column.cpp
> +        std::is_same<T, typename DateTimeArrayType::value_type>::value);
I'm saying the templates may use value_type as T directly, practically removing T. That's in the direction I'm expecting to go where Table/Column will become thinner and thinner wrappers on top of Arrow

2020-10-16 18:43 UTC, roshandathathri commented on libquery/src/Column.cpp
> +        std::is_same<T, typename DateTimeArrayType::value_type>::value);
Ok, sounds good.

2020-10-16 19:09 UTC, merged