Add function to return path for csv datasets
KatanaGraph/katana pull request #653
Opened 2021-10-28 01:20 UTC by bhargavivadali

Updated example_data.py to add a function to return path for csv datasets

2021-10-28 02:40 UTC, gliga commented on python/katana/example_data.py
> +    path = Path(__file__).parent.parent.parent.parent.parent.parent.parent.parent / "katana-enterprise/external/csv-datasets"
can you leverage `get_inputs_directory`?  This parent.parent.parent is very fragile (if we start moving files around).
Can you use `get_input` in this case too?  get_input should not be specific to RDGs

2021-10-28 18:34 UTC, arthurp requested changes

2021-10-28 18:34 UTC, arthurp commented on python/katana/example_data.py
> +    path = Path(__file__).parent.parent.parent.parent.parent.parent.parent.parent / "katana-enterprise/external/csv-datasets"
This assumes got is running in a build directory. This is not a valid assumption for this code. The other code here will actually automatically download the data from S3 if it isn't available and cache it in the users home directory. And this will work even in user installs.

If you want to have this function here, I would recommend you do as @gliga says and put your data in the same inputs blob as the RDGs. If that's not possible or practical, then this function needs to be used to a non-user visible part of the system or at least hidden in an obviously internal package like a `katana.testing.data` package or something.

Whichever you think is appropriate is fine.

2021-10-29 16:59 UTC, bhargavivadali commented on python/katana/example_data.py
> +    path = Path(__file__).parent.parent.parent.parent.parent.parent.parent.parent / "katana-enterprise/external/csv-datasets"
CSV data is already present in katana-enterprise/external dir. I was trying to fetch its path. I removed the new function and using get_input and get_inputs_director.

2021-11-01 19:23 UTC, bhargavivadali commented
Closing this PR. I'll create another PR with all the changes.

2021-11-01 19:23 UTC, closed without merging