Add a mechanism to bypass system random number generator
KatanaGraph/katana pull request #654
Opened 2021-10-28 19:34 UTC by aneeshdurg

This will be used in tests to be able to "replay" a test from CI using the same seed.

JIRA: KAT-2158

2021-10-28 19:41 UTC, scober commented on libsupport/test/random.cpp
> +  auto val2 = katana::RandomAlphanumericString(12, &gen2);
Would it be correct to `KATANA_LOG_ASSERT(seed1 == seed2)`?

2021-10-28 19:48 UTC, aneeshdurg commented on libsupport/test/random.cpp
> +  auto val2 = katana::RandomAlphanumericString(12, &gen2);
good point, yes

2021-10-28 19:50 UTC, scober approved these changes

2021-10-28 19:50 UTC, scober commented on libsupport/include/katana/Random.h
> +KATANA_EXPORT RandGenerator& GetGenerator(
Is this mostly for backwards compatiblity? It seems safe to always return the seed.

2021-10-28 19:50 UTC, scober commented on libsupport/src/Random.cpp
> +    std::seed_seq seq(std::begin(*seed_in), std::end(*seed_in));
I didn't know you could dereference optionals. Very fun.

2021-10-28 19:52 UTC, aneeshdurg commented on libsupport/include/katana/Random.h
> +KATANA_EXPORT RandGenerator& GetGenerator(
This method might return the previously created generator, which may have used a different seed. I can just have this method not take in a seed at all if you feel like that might be clearer.

2021-10-28 20:50 UTC, amberhassaan reviewed
Important question regarding atomic initialization needs a resolution.

2021-10-28 20:50 UTC, amberhassaan commented on libsupport/src/Random.cpp
> +std::pair<T, katana::Seed>
why are we returning a seed?

2021-10-28 20:50 UTC, amberhassaan commented on libsupport/src/Random.cpp
> +    return std::make_pair(katana::RandGenerator(seq), *seed_in);
This path does not use a lock to protect the update to thread_local variable `kRNG`. See the lock being used on line 92. 

@ddn0  : I don't understand why the lock isn't around line 79 (instead of line 94). Can you help clarify the reasoning? I believe it should be at line 79 where `kRNG` is being initialized for the first time.

2021-10-28 20:56 UTC, aneeshdurg commented on libsupport/src/Random.cpp
> +std::pair<T, katana::Seed>
We're currently seeing some non-deterministic tests fail in CI, if we return the seed, we could log the seed used by random-oec, and the reproduce the failures

2021-10-28 20:57 UTC, amberhassaan commented on libsupport/src/Random.cpp
> +std::pair<T, katana::Seed>
ok, got it.

2021-10-28 21:00 UTC, amberhassaan commented on libsupport/src/Random.cpp
> +    return std::make_pair(katana::RandGenerator(seq), *seed_in);
Oh, OK, I wasn't looking at the right code. The previous state of the code does protect `kRNG`'s initialization. @aneeshdurg : please make sure that this invariant stays true here as well and move the lock to line 79.

2021-10-28 21:27 UTC, aneeshdurg commented on libsupport/src/Random.cpp
> +    return std::make_pair(katana::RandGenerator(seq), *seed_in);
my mistake, I moved things around without reading.

2021-10-28 22:15 UTC, tylershunt requested changes

2021-10-28 22:15 UTC, tylershunt commented on libsupport/src/Random.cpp
> +  kRNG = std::make_unique<RandGenerator>(std::get<0>(result));
Overriding this with a seeded generator has the potential create problems with parts of the code that actually rely on randomness, e.g., coming up with different filenames for properties.  I think now if every host provides the same seed filenames will collide and invariants will break.

Can we have a solution that doesn't assume that everyone wants determinism when some part of the code base seeds this generator?

Fwiw. We made it thread local and persistent because we were exhausting system randomness in CI, there's no reason to restrict the creation of deterministically seeded generators.

2021-10-29 15:45 UTC, aneeshdurg commented on libsupport/src/Random.cpp
> +  kRNG = std::make_unique<RandGenerator>(std::get<0>(result));
yeah, we can have this method not allow the user to pass in a seed, and only use CreateGenerator for seeded randomness

2021-10-29 16:10 UTC, tylershunt commented on libsupport/src/Random.cpp
> +  kRNG = std::make_unique<RandGenerator>(std::get<0>(result));
Thanks!

2021-10-29 16:16 UTC, tylershunt approved these changes

2021-10-29 16:16 UTC, tylershunt commented on libsupport/include/katana/Random.h
> +/// \returns a random number generator. The generator is local to the calling
Sorry to be a pain but could you update this comment to restore the statement about `GetGenerator()` always returning a generator seeded with system randomness.

2021-10-29 17:01 UTC, merged