Shared memory Louvain: Add int64 edge property to the property graph (if edge weight input is either of type int32 or uint32)
KatanaGraph/katana pull request #667
Opened 2021-11-03 22:44 UTC by uditagar

This PR adds the functionality to the shared memory louvain app to allow the edge weights to be converted to int64 type, if the input edge weights are of type int32 or uint32. This is required since the edge weights in the coarsened graph can fall into the range of int64.

2021-11-04 23:57 UTC, roshandathathri approved these changes
LGTM

2021-11-04 23:57 UTC, roshandathathri commented on libgalois/src/analytics/louvain_clustering/louvain_clustering.cpp
> +      katana::steal(), katana::loopname("CopyEdgeWeight"));
Drop steal()

2021-11-05 00:17 UTC, uditagar commented
I wanted to ask if we need to push this for alpha or not, since it seems that there is still some problem with it with rmat10 test cases.

2021-11-11 00:36 UTC, gurbinder533 requested changes

2021-11-11 00:36 UTC, gurbinder533 commented on libgalois/src/analytics/louvain_clustering/louvain_clustering.cpp
> +  TemporaryPropertyGuard temporary_edge_property{pg->EdgeMutablePropertyView()};
I don't think we should add another temp edge_property to the original graph. Please convert the edge-property to int64 when creating duplicate graph to work on.

2022-05-06 22:20 UTC, closed without merging