build: Avoid reusing cached values across find_c_library invocations
KatanaGraph/katana pull request #754
Opened 2021-12-14 22:57 UTC by ddn0

Both find_path and find_library cache their results, which can cause
find_c_library to return paths for unrelated libraries. Avoid this issue
by using result variables tied to the library being searched for.

2021-12-14 23:44 UTC, chakpongchung approved these changes
LGTM

Thanks!

2021-12-15 20:57 UTC, arthurp approved these changes

2021-12-16 02:12 UTC, chakpongchung requested changes
@ddn0 
sorry, please do not merge it yet. I am seeing problems here when using ubuntu 20.04 and conan build or using APT only. 

Looks like I can reproduce the issue locally:

```
CMake Error at external/katana/cmake/Modules/FindCLibrary.cmake:83 (message):
  antlr4-runtime not found
```


Will report back.

2021-12-16 03:17 UTC, arthurp commented
> Will report back.

You will want to look at the output of `env` and full cmake command lines. It's impossible to tell what cmake is searching without looking at the details of the environment.

2021-12-16 03:40 UTC, chakpongchung commented
> > Will report back.
> 
> You will want to look at the output of `env` and full cmake command lines. It's impossible to tell what cmake is searching without looking at the details of the environment.

env:

```
SHELL=/bin/bash
SESSION_MANAGER=local/cpchung:@/tmp/.ICE-unix/2790,unix/cpchung:/tmp/.ICE-unix/2790
QT_ACCESSIBILITY=1
COLORTERM=truecolor
GCC_RANLIB=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-gcc-ranlib
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
XDG_MENU_PREFIX=gnome-
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
CONDA_MKL_INTERFACE_LAYER_BACKUP=
CONDA_EXE=/home/cpchung/miniconda3/envs/katana-dev/bin/conda
_CE_M=
TERMINAL_EMULATOR=JetBrains-JediTerm
AWS_EC2_METADATA_DISABLED=true
build_alias=x86_64-conda-linux-gnu
CMAKE_ARGS=-DCMAKE_AR=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-ar -DCMAKE_CXX_COMPILER_AR=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_C_COMPILER_AR=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_RANLIB=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-ranlib -DCMAKE_CXX_COMPILER_RANLIB=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_C_COMPILER_RANLIB=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_LINKER=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-ld -DCMAKE_STRIP=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-strip
GPROF=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-gprof
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/
CONDA_TOOLCHAIN_BUILD=x86_64-conda-linux-gnu
GNOME_SHELL_SESSION_MODE=ubuntu
_CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
STRINGS=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-strings
CPP=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-cpp
JAVA_LD_LIBRARY_PATH=/home/cpchung/miniconda3/envs/katana-dev/lib/server
TERM_SESSION_ID=d122bb6a-497a-4687-979a-bcf035d01056
XMODIFIERS=@im=ibus
DESKTOP_SESSION=ubuntu
SSH_AGENT_PID=2717
GTK_MODULES=gail:atk-bridge
PWD=/home/cpchung/kg/forked/katana-enterprise
GSETTINGS_SCHEMA_DIR=/home/cpchung/miniconda3/envs/katana-dev/share/glib-2.0/schemas
XDG_SESSION_DESKTOP=ubuntu
LOGNAME=cpchung
XDG_SESSION_TYPE=x11
CONDA_PREFIX=/home/cpchung/miniconda3/envs/katana-dev
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
GSETTINGS_SCHEMA_DIR_CONDA_BACKUP=
CXX=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-c++
CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/cpchung/miniconda3/envs/katana-dev/include
XAUTHORITY=/run/user/1000/gdm/Xauthority
CONDA_TOOLCHAIN_HOST=x86_64-conda-linux-gnu
DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /home/cpchung/miniconda3/envs/katana-dev/include
WINDOWPATH=2
LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/cpchung/miniconda3/envs/katana-dev/lib -Wl,-rpath-link,/home/cpchung/miniconda3/envs/katana-dev/lib -L/home/cpchung/miniconda3/envs/katana-dev/lib
HOME=/home/cpchung
USERNAME=cpchung
IM_CONFIG_PHASE=1
LANG=en_US.UTF-8
DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /home/cpchung/miniconda3/envs/katana-dev/include
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
XDG_CURRENT_DESKTOP=ubuntu:GNOME
VTE_VERSION=6003
CXX_FOR_BUILD=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-c++
ELFEDIT=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-elfedit
CONDA_PROMPT_MODIFIER=(katana-dev) 
CMAKE_PREFIX_PATH=/home/cpchung/miniconda3/envs/katana-dev:/home/cpchung/miniconda3/envs/katana-dev/x86_64-conda-linux-gnu/sysroot/usr
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/ea01d0da_b561_4954_8ef9_83fe872c60e3
CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/cpchung/miniconda3/envs/katana-dev/include
LD=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-ld
INVOCATION_ID=b5db133655ae4e69a5873e0614debb9a
MANAGERPID=2523
GOROOT=/home/cpchung/miniconda3/envs/katana-dev/go
READELF=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-readelf
GXX=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-g++
JAVA_LD_LIBRARY_PATH_BACKUP=
GCC_AR=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-gcc-ar
LESSCLOSE=/usr/bin/lesspipe %s %s
ADDR2LINE=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-addr2line
XDG_SESSION_CLASS=user
CONDA_BACKUP_GOROOT=
TERM=xterm-256color
_CE_CONDA=
GCC_NM=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-gcc-nm
SIZE=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-size
HOST=x86_64-conda-linux-gnu
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
LESSOPEN=| /usr/bin/lesspipe %s
CC_FOR_BUILD=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-cc
USER=cpchung
GNOME_TERMINAL_SERVICE=:1.124
CONDA_SHLVL=1
AR=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-ar
AS=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-as
DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem /home/cpchung/miniconda3/envs/katana-dev/include
host_alias=x86_64-conda-linux-gnu
DISPLAY=:0
SHLVL=3
NM=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-nm
GCC=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-gcc
QT_IM_MODULE=ibus
LD_GOLD=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-ld.gold
CONDA_PYTHON_EXE=/home/cpchung/miniconda3/envs/katana-dev/bin/python
XDG_RUNTIME_DIR=/run/user/1000
CONDA_DEFAULT_ENV=katana-dev
OBJCOPY=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-objcopy
JAVA_HOME_CONDA_BACKUP=/usr/lib/jvm/java-17-openjdk-amd64/
STRIP=/home/cpchung/miniconda3/envs/katana-dev/bin/x86_64-conda-linux-gnu-strip
JOURNAL_STREAM=9:65968
XDG_DATA_DIRS=/usr/share [...]

2021-12-16 04:01 UTC, chakpongchung commented
One more issue found here:
https://github.com/KatanaGraph/katana-enterprise/pull/2681#issuecomment-995414880

2021-12-16 14:28 UTC, chakpongchung commented
> > Will report back.
> 
> You will want to look at the output of `env` and full cmake command lines. It's impossible to tell what cmake is searching without looking at the details of the environment.

Thanks, `find_library` is solved by setting the following:
```
  set(CMAKE_LIBRARY_ARCHITECTURE x86_64-linux-gnu)
```

2021-12-16 16:28 UTC, chakpongchung approved these changes

2021-12-16 18:36 UTC, merged