[KAT-2749] Add bindings for certain additional entity type manager methods
KatanaGraph/katana pull request #847
Opened 2022-01-29 02:12 UTC by denish44

EntityTypeManager have some methods that aren't exposed in the python binding. This PR adds additional methods to the python wrapper which logically makes sense to expose.

Jira: KAT-2749

2022-01-31 20:58 UTC, denish44 commented
@bowu @arthurp This PR adds methods I think makes sense for exposure. Please let me know if there is need to expose additional things. But think this in general provides enough functionality to do what's needed with entity type manager.

2022-01-31 21:08 UTC, bowu commented
I added @sanchveda as a reviewer because he tried to implement NARS in Katana, which needed type info exposed in this PR. @sanchveda Could you please let us know whether the API is enough for you to implement NARS?

2022-01-31 21:35 UTC, arthurp requested changes
If there are any methods that will take more than a trivial amount of time (microseconds), add `py::call_guard<py::gil_scoped_release>()` as discussed here: https://pybind11.readthedocs.io/en/stable/advanced/misc.html#global-interpreter-lock-gil. Make sure the method doesn't access any python objects though.

2022-01-31 21:35 UTC, arthurp commented on libkatana_python_native/src/EntityTypeManager.cpp
> +          &katana::EntityTypeManager::GetNumEntityTypes);
`GetNumEntityTypes` should be called as `num_types` (all types are entity types). `GetNumAtomicTypes` should be called as `num_atomic_types`.

The `Get` at the beginning is an oddity even in C++.

2022-01-31 21:35 UTC, arthurp commented on libkatana_python_native/src/EntityTypeManager.cpp
> +                    ret.add(AtomicEntityType{{self, subtype_id}});
You don't need the check. The type is an atomic type since it was returned from `GetAtomicSubtypes`.

2022-01-31 21:35 UTC, arthurp commented on libkatana_python_native/src/EntityTypeManager.cpp
> +                   ++subtype_id) {
This isn't very efficient. It iterates over every bit in the vector, not just the ones. I don't think we should fix it now, but please add a TODO and file an issue against `DynamicBitSet` to add a method that efficiently finds ones (by iterating over 64-bit words and doing bit magic). That would help a lot with this and should be reasonably fast.

2022-01-31 22:50 UTC, denish44 commented
> If there are any methods that will take more than a trivial amount of time (microseconds), add `py::call_guard<py::gil_scoped_release>()` as discussed here: https://pybind11.readthedocs.io/en/stable/advanced/misc.html#global-interpreter-lock-gil. Make sure the method doesn't access any python objects though.

I don't think we need to worry about this. with the new exposure and old exposure, I think the worst case scenario is O(types) in any method which has a bound so mostly O(1) theoretically.

2022-02-01 00:59 UTC, sanchveda reviewed
@bowu I guess for NARS, the only thing I would require is to get a view from a set of different types and then a way to get the local ids of the individual nodes in the view. That should be sufficient of it's implementation.

2022-02-01 01:03 UTC, denish44 commented
> @bowu I guess for NARS, the only thing I would require is to get a view from a set of different types and then a way to get the local ids of the individual nodes in the view. That should be sufficient of it's implementation.

node ids? this manager is only for type ids ? I don't think this has anything to do with views unless i misunderstood something.

2022-02-01 15:28 UTC, bowu commented
@denish44 What Sanchayan meant is that he mainly cares about projected view instead of types. I believe Arthur is working on view APIs.

2022-02-01 15:46 UTC, arthurp commented
> @denish44 What Sanchayan meant is that he mainly cares about projected view instead of types. I believe Arthur is working on view APIs.

Yep. Though projected views will come slightly after the other views because it's getting a rework in C++ right now. Should land soon.

2022-02-01 15:49 UTC, arthurp approved these changes
LGTM.

2022-02-01 15:49 UTC, arthurp commented on python/test/test_property_graph.py
> +        set([node_atomic_types["Message"], non_atomic_type])
NIT: You shouldn't need the set constructor here. You can pass any collection, I think. Also Set literals are supported in python. They look like this: `{a, b, c}`. They look a LOT like dict literals though (only differing by the colons), so I kinda prefer the constructor form anyway.

2022-02-01 19:58 UTC, merged